// General config

export const siteConfig = {
  title: 'Register Rescue RS',
  description: 'Generated by create next app',
} satisfies Record<string, string>

export type RouteVisibility = 'public' | 'protected'

export type Contributor = {
  user: string
  href: string
}

export const mainContributors = [
  {
    user: 'caieradev',
    href: 'https://github.com/caieradev',
  },
  {
    user: 'lorenzoa7',
    href: 'https://github.com/lorenzoa7',
  },
  {
    user: 'arthuroli29',
    href: 'https://github.com/arthuroli29',
  },
  {
    user: 'GuiAguirres',
    href: 'https://github.com/GuiAguirres',
  },
  {
    user: 'luilencina',
    href: 'https://github.com/luilencina',
  },
  {
    user: 'gbombassaro',
    href: 'https://github.com/gbombassaro',
  },
  {
    user: 'caiocesarbrito',
    href: 'https://github.com/caiocesarbrito',
  },
] satisfies Contributor[]

export const organizationHref = 'https://github.com/ResgateRS'

export const whatsappHref =
  'https://wa.me/55XXXXXXXXXXX?text=Olá!%20Gostaria%20de%20solicitar%20um%20cadastro!'

// Site routes

export const prefixSiteRoutes = {
  protected: '/meu-abrigo',
  public: '',
} as const satisfies Record<RouteVisibility, string>

export const siteRoutes = {
  public: {
    landingPage: `${prefixSiteRoutes.public}/`,
    login: `${prefixSiteRoutes.public}/login`,
    donations: `${prefixSiteRoutes.public}/doacoes`,
    volunteers: `${prefixSiteRoutes.public}/voluntarios`,
  },
  protected: {
    families: `${prefixSiteRoutes.protected}/familias`,
  },
} as const satisfies Record<RouteVisibility, Record<string, string>>
