// General config

export const siteConfig = {
  title: 'Register Rescue RS',
  description: 'Generated by create next app',
} satisfies Record<string, string>

export type RouteVisibility = 'public' | 'protected'

export type Contributor = {
  user: string
  href: string
}

export const mainContributors = [
  {
    user: 'caieradev',
    href: 'https://github.com/caieradev',
  },
  {
    user: 'lorenzoa7',
    href: 'https://github.com/lorenzoa7',
  },
] satisfies Contributor[]

export const repositoryHref =
  'https://github.com/caieradev/RegisterRescueRS-Front'

// Site routes

export const prefixSiteRoutes = {
  protected: '/app',
  public: '',
} as const satisfies Record<RouteVisibility, string>

export const siteRoutes = {
  public: {
    landingPage: `${prefixSiteRoutes.public}/`,
    login: `${prefixSiteRoutes.public}/login`,
    donations: `${prefixSiteRoutes.public}/doacoes`,
    volunteers: `${prefixSiteRoutes.public}/voluntarios`,
  },
  protected: {
    families: `${prefixSiteRoutes.protected}/familias`,
  },
} as const satisfies Record<RouteVisibility, Record<string, string>>
