// General config

export const siteConfig = {
  title: 'Register Rescue RS',
  description: 'Generated by create next app',
} satisfies Record<string, string>

export type RouteVisibility = 'public' | 'protected'

export const prefixSiteRoutes = {
  protected: '/app',
  public: '',
} as const satisfies Record<RouteVisibility, string>

// Site routes

export const siteRoutes = {
  public: {
    landingPage: `${prefixSiteRoutes.public}/`,
    login: `${prefixSiteRoutes.public}/login`,
    donations: `${prefixSiteRoutes.public}/doacoes`,
    volunteers: `${prefixSiteRoutes.public}/voluntarios`,
  },
  protected: {
    families: `${prefixSiteRoutes.protected}/familias`,
  },
} as const satisfies Record<RouteVisibility, Record<string, string>>
